#! /bin/bash

#check the first argument for start or end of officetime
if [ "$1" == 'start' ];
then
  slack & 
  #google-chrome & 
  #code &
  /opt/brave.com/brave/brave-browser &
  /opt/PhpStorm-193.5233.101/bin/phpstorm.sh &
  /home/anand/Hubstaff/HubstaffClient.bin.x86_64 &
  #sudo /opt/lampp/xampp start &
fi

if [[ ( "$1" == 'stop' || "$1" == 'end' ) ]];
then
  pkill slack 
  #pkill chrome
  #pkill code
  pkill /opt/brave.com/brave/brave-browser
  pkill /opt/PhpStorm-193.5233.101/bin/phpstorm.sh
  pkill /home/anand/Hubstaff/HubstaffClient.bin.x86_64
  #sudo /opt/lampp/xampp stop
fi
